-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHCwcFrDc4DLpO+wl
3B+l5vaqlbCOy56Rd3xsCN7PvSigCgYIKoZIzj0DAQehRANCAARlPWQKegXF8g3g
NsU0ItrhPa++FutoBD/vjW8FQ1DDg1Y0/jiCbIR6dv5jkVgjNcZx7sO7dTik8hgB
hxHk+FPb
-----END PRIVATE KEY-----